// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTAmt9lZPTCqgo1dYj-Pz3B9s2t5nqGe8',
    appId: '1:297824287206:web:5582d823bd31686b01be27',
    messagingSenderId: '297824287206',
    projectId: 'fruits-hup-1f77f',
    authDomain: 'fruits-hup-1f77f.firebaseapp.com',
    storageBucket: 'fruits-hup-1f77f.firebasestorage.app',
    measurementId: 'G-TQHVBVTY5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzws90TN2CF8sUwfawBYsqkCV2maW15tg',
    appId: '1:297824287206:android:1acaf57490bb1e7501be27',
    messagingSenderId: '297824287206',
    projectId: 'fruits-hup-1f77f',
    storageBucket: 'fruits-hup-1f77f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc-X5j_MYer_dzgGBwelR-MgCRTBqrnOc',
    appId: '1:297824287206:ios:0df8288125877d4c01be27',
    messagingSenderId: '297824287206',
    projectId: 'fruits-hup-1f77f',
    storageBucket: 'fruits-hup-1f77f.firebasestorage.app',
    androidClientId: '297824287206-nvo344asobnoeb9pjfhsv15hppvk06lp.apps.googleusercontent.com',
    iosClientId: '297824287206-uudod2sqd9mj5fu9d701s1s1qbnjej5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc-X5j_MYer_dzgGBwelR-MgCRTBqrnOc',
    appId: '1:297824287206:ios:0df8288125877d4c01be27',
    messagingSenderId: '297824287206',
    projectId: 'fruits-hup-1f77f',
    storageBucket: 'fruits-hup-1f77f.firebasestorage.app',
    androidClientId: '297824287206-nvo344asobnoeb9pjfhsv15hppvk06lp.apps.googleusercontent.com',
    iosClientId: '297824287206-uudod2sqd9mj5fu9d701s1s1qbnjej5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTAmt9lZPTCqgo1dYj-Pz3B9s2t5nqGe8',
    appId: '1:297824287206:web:2819aaf7e2624e1d01be27',
    messagingSenderId: '297824287206',
    projectId: 'fruits-hup-1f77f',
    authDomain: 'fruits-hup-1f77f.firebaseapp.com',
    storageBucket: 'fruits-hup-1f77f.firebasestorage.app',
    measurementId: 'G-RQXBEBEJN6',
  );
}
